site_name: Sistema de señalética de los buses de la Universidad de Costa Rica

nav:
    - Inicio: index.md
    - Elementos: elementos.md
    - Infraestructura: infraestructura.md
    - Databús: databus.md
    - Infobús: infobus.md
    - Vehículos: vehiculos.md
    - Impresiones: impresiones.md
    - Sitios web: web.md
    - GTFS: gtfs.md
    - Sobre: sobre.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: es
  palette:
    scheme: ucr
  logo: assets/logos/b_blanco.png
  favicon: assets/logos/b_azul.png
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.footer
    - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://github.com/fabianabarca/senaletica
repo_name: fabianabarca/senaletica

extra:
  generator: false